#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ruby_build',
  :git => 'git://github.com/fnichol/chef-ruby_build.git', 
  :ref => 'v0.6.0'
cookbook 'redisio'
cookbook 'apt'
cookbook 'nodejs'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'vim'
cookbook 'postgresql'
cookbook 'postgis'
cookbook 'rails-lastmile',
  :path => 'vendor/rails-lastmile'
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
